### ISSUE TITLE
[Feat] 정원 방문 기능 구현

### ISSUE THREAD

**Issue by mjeong21** [wantPlant/wantPlant_AFE#15]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
- 정원 방문 기능 구현

## ✅ To-Do
> 작업 계획 작성
- [ ] 정원 생성이 3개가 넘어가지 않도록
- [ ] 정원 만들기를 누르면 정원 생성으로 이동
- [ ] 화분 심기를 누르면 화분 심기로 이동
- [ ] 데이터 저장 (정원 이름, 정원 별 화분)
