### ISSUE TITLE
[Feat] 이메일 찾기1 ui 구현

### ISSUE THREAD

**Issue by 2hyunjinn** [wantPlant/wantPlant_AFE#2]
## 📄 작업 내용

---

- 이메일 찾기1 ui 구현

## ✅ To-Do

---

- [x]  이름 입력창 구현
- [x]  휴대폰 번호 입력창 구현
- [x]  확인 버튼 구현
