### ISSUE TITLE
[Feat] 사용 설명서 기능 구현

### ISSUE THREAD

**Issue by asjasj3964** [wantPlant/wantPlant_AFE#37]
## 📄 작업 내용
- 사용 설명서 기능 구현

## ✅ To-Do
- [x] 손으로 좌우 스와이프하여 사용 설명서 및 자주 묻는 질문 넘기기
- [x] 각 탭을 클릭했을 때 해당 페이지가 나오게 하기 (선택된 탭에 변화 주기)
- [x] 자주 묻는 질문 토글 (세모 아이콘, 답변) 적용하기
