### ISSUE TITLE
[Feat] 정원 방문 API 연동

### ISSUE THREAD

**Issue by 2hyunjinn** [wantPlant/wantPlant_AFE#52]
## 📄 작업 내용
> 구현 목표에 대한 설명 작성
-  정원 방문 API 연동

## ✅ To-Do
> 작업 계획 작성
- [ ] 정원 이름 누르면 해당 화분 리스트 GET
- [ ] 정원 이름 누르면 해당 화분 리스트로 보여지도록 view 구현
- [ ] 정원 배경 누르면 전체도감으로 뷰 이동
- [ ] 정원 전체 리스트 GET
- [ ] 정원 이름 리사이클러뷰로 보여지도록 view 구현
